#!/usr/bin/env python3
"""Verify the current ClassicAPI audit and generated README index, without network access.

Run with --write to refresh only the marked README block. Audit contents are preserved.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BEGIN = "<!-- BEGIN CLASSICAPI AUDIT INDEX -->"
END = "<!-- END CLASSICAPI AUDIT INDEX -->"
VERSION = re.compile(r"[0-9]+\.[0-9]+\.[0-9]+")
AUDIT_NAME = re.compile(r"CLASSICAPI_([0-9]+\.[0-9]+\.[0-9]+)_AUDIT\.md")


class AuditIndexError(ValueError):
    pass


def version_key(version: str) -> tuple[int, ...]:
    return tuple(int(part) for part in version.split("."))


def build_index(root: Path) -> str:
    config = json.loads((root / "UPSTREAM_VERSIONS.json").read_text(encoding="utf-8"))
    component = config.get("classicapi") if isinstance(config, dict) else None
    version = component.get("reference_version") if isinstance(component, dict) else None
    if not isinstance(version, str) or VERSION.fullmatch(version) is None:
        raise AuditIndexError("classicapi.reference_version must be a numeric X.Y.Z release version")

    current = root / "docs" / f"CLASSICAPI_{version}_AUDIT.md"
    if not current.is_file():
        raise AuditIndexError(f"Missing current ClassicAPI audit: docs/{current.name}")

    audits = []
    for path in (root / "docs").glob("CLASSICAPI_*_AUDIT.md"):
        match = AUDIT_NAME.fullmatch(path.name)
        if match is None or not path.is_file():
            raise AuditIndexError(f"Invalid release audit file: docs/{path.name}")
        audits.append((match.group(1), path.name))

    lines = [
        BEGIN,
        "<!-- Generated by tools/check_audit_index.py from UPSTREAM_VERSIONS.json and docs/CLASSICAPI_*_AUDIT.md. -->",
        "",
        "| Audit | Status |",
        "| --- | --- |",
    ]
    for release, filename in sorted(audits, key=lambda audit: version_key(audit[0]), reverse=True):
        if release == version:
            status = "Current reference"
        elif version_key(release) < version_key(version):
            status = "Historical release audit"
        else:
            status = "Other release audit"
        lines.append(f"| [v{release} audit](docs/{filename}) | {status} |")
    lines.extend(("", END))
    return "\n".join(lines)


def reconcile(root: Path, *, write: bool = False) -> bool:
    index = build_index(root)
    readme = root / "README.md"
    original_bytes = readme.read_bytes()
    original = original_bytes.decode("utf-8").replace("\r\n", "\n")
    if original.count(BEGIN) != 1 or original.count(END) != 1:
        raise AuditIndexError("README must contain exactly one pair of ClassicAPI audit index markers")
    start = original.index(BEGIN)
    end = original.index(END)
    if end < start:
        raise AuditIndexError("README ClassicAPI audit index markers are reversed")
    updated = original[:start] + index + original[end + len(END):]
    if updated == original:
        return False
    if not write:
        raise AuditIndexError("README audit index is stale; run: python tools/check_audit_index.py --write")
    newline = "\r\n" if b"\r\n" in original_bytes else "\n"
    readme.write_bytes(updated.replace("\n", newline).encode("utf-8"))
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT, help="VanillaForge repository root")
    parser.add_argument("--write", action="store_true", help="Refresh the marked README audit index")
    args = parser.parse_args(argv)
    try:
        changed = reconcile(args.root, write=args.write)
    except (AuditIndexError, OSError, UnicodeError, json.JSONDecodeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    print("README audit index updated." if changed else "Current ClassicAPI audit and README index verified.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
